#!/bin/bash
default_path="pack/default/start/"
if [ $# -eq 1 ]; then
    plg_path="$default_path$1"
elif [ $# -eq 2 ]; then
    plg_path="pack/$1/start/$2"
fi
git submodule deinit $plg_path
git rm -r -f $plg_path
rm -rf .git/modules/$plg_path
git commit
